### ISSUE TITLE
P11 - Modified Encoding

### ISSUE THREAD

**Issue by taiheng** [eneko/Ninety-Nine-Swift-Solutions#20]
[Problem 11](http://www.enekoalonso.com/projects/99-swift-problems/#p11) tester is expecting a solution of 

```
List<Any>(List<Any>(4, "a"), "b", List<Any>(2, "c"), List<Any>(2, "a"), "d", List<Any>(4, "e"))
```

but the problem statement is asking for:
```
List<Any>((4, "a"), "b", (2, "c"), (2, "a"), "d", (4, "e"))
```

Which one is the correct one?

**Comment by dukevantreta** [comment]
I stumbled upon this issue too. 
`List<Any>(4, "a")` is initialized as a 2-element list. When it is printed, it is described as `[4, a]` instead of `[(4, "a")]`, and this happens recursively when describing the string.

To achieve the desired effect and staying true to the problem, I propose that the P11 tester's target lists should be initialized as 
```
// Encoding letters test
List<Any>((4, "a"), "b", (2, "c"), (2, "a"), "d", (4, "e"))
// Encoding numbers test
List<Any>((2, 1), 2, 3, 5, 8)
```

**Comment by eneko** [comment]
Hello @taiheng & @MisterVants. Apologies for the late response, just reading this issue.

I agree the test looks incorrect, as it does not match the description of the problem. I'll work on fixing the test.

Thank you!
